from selenium import webdriver
import time
import random
#options = webdriver.ChromeOpti­ons()
#options.add_argument­( '--ignore-certificat­e-errors' )
#options.add_argument­( "--test-type" )
profile = webdriver.FirefoxProfile()
#profile.set_preference("network.proxy.type", 1)
#profile.set_preference("network.proxy.http" ,PROXY_HOST )
#profile.set_preference( "network.proxy.http_port" ,int(PROXY_PORT))
profile.set_preference( "general.useragent.override" ,"'Mozilla/5.0(Macintosh; Intel Mac OS X 10_11_6)AppleWebKit/537.36 (KHTML, like Gecko)Chrome/55.0.2883.95 Safari/537.36'" )
path1 = 'geckodriver.exe'
profile.update_preferences()
driver = webdriver.Firefox(executable_path = path1,firefox_profile = profile)
driver.set_window_size(320 , 480)
driver.get( 'http://127.0.0.1:8000/' )
time.sleep(2)
driver.save_screenshot( "mk\{s}.png".format(s = random.randint(1098, 10000476)) )
driver.close()
#req = Request('http://deloplen.com/afu.php?zoneid=1407888&var=2747633')
#req.set_proxy('{p}:{n}'.format(p = ma[m]['ip'], n = ma[m]['port']),'http' or 'socks5')
#req.add_header('User-Agent',ua.random)
#opener = build_opener()
#req.set_proxy(ma[m]['ip']+':'+ma[m]['port'],'http')
#doc = urlopen(req).read().decode('utf8')
#u = opener.open(req)
#print(doc)
#time.sleep(2)
"""#req = Request('http://deloplen.com/afu.php?zoneid=1407888&var=2747633')
        req = Request('https://iplogger.org/2qq6P5')
        req.set_proxy('{p}:{n}'.format(p = ma[m]['ip'], n = ma[m]['port']),'http' or 'socks5')
        req.add_header('User-Agent',ua.random)
        opener = build_opener()
        #req.set_proxy(ma[m]['ip']+':'+ma[m]['port'],'http')
        doc = urlopen(req).read().decode('utf8')
        #u = opener.open(req)
        print('good')
        time.sleep(2)
        req = Request('http://www.murl.mobi/headers.php')
        req.set_proxy('{p}:{n}'.format(p = ma[m]['ip'], n = ma[m]['port']),'http' or 'socks5')
        req.add_header('User-Agent',ua.random)
        opener = build_opener()
        #req.set_proxy(ma[m]['ip']+':'+ma[m]['port'],'http')
        doc = urlopen(req).read().decode('utf8')
        #u = opener.open(req)
        print(doc)
        time.sleep(2)
        """
profile = webdriver.FirefoxProfile()
        #i cant diny it ovious #i see you in aNything
        profile.set_preference("network.proxy.type", 1)
        profile.set_preference("network.proxy.http" ,"{ip}".format(ip =ma[m]['ip']))
        profile.set_preference( "network.proxy.http_port" ,int(ma[m]['port']))
        profile.set_preference("network.proxy.https" ,"{ip}".format(ip =ma[m]['ip']))
        profile.set_preference( "network.proxy.https_port" ,int(ma[m]['port']))
        profile.set_preference("network.proxy.ssl" ,"{ip}".format(ip =ma[m]['ip']))
        profile.set_preference( "network.proxy.ssl_port" ,int(ma[m]['port']))
        profile.set_preference("network.proxy.ftp" ,"{ip}".format(ip =ma[m]['ip']))
        profile.set_preference( "network.proxy.ftp_port" ,int(ma[m]['port']))
        profile.set_preference("network.proxy.socks" ,"{ip}".format(ip =ma[m]['ip']))
        profile.set_preference( "network.proxy.socks_port" ,int(ma[m]['port']))
        profile.set_preference( "general.useragent.override" ,ua.random)
        path1 = 'geckodriver.exe'
        profile.update_preferences()
        driver = webdriver.Firefox(executable_path = path1,firefox_profile = profile)
        driver.set_window_size(320 , 480)
        driver.get('https://iplogger.org/2qq6P5')
        time.sleep(2)
        driver.save_screenshot( "mk\{s}.png".format(s = random.randint(1098, 10000476)) )
        driver.close()
"""socks.setdefaultproxy(socks.PROXY_TYPE_SOCKS5,ma[m]['ip'],ma[m]['port'])
# patch the socket module
socket.socket = socks.socksocket
socket.create_connection = create_connection
br = Browser()
br.set_handle_robots(False)
br.set_handle_equiv(False)
br.addheaders = [('User-Agent', ua.random)]
response = br.open('https://azenv.net')
print(response.read())
time.sleep(2)
break"""
